name: "A+: CI"

permissions:
  contents: write

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
  push:
    branches:
      - main

jobs:
  cargo-build:
    name: Cargo Build
    runs-on: ubuntu-latest

    steps:
      - name: Fetch Repository
        uses: actions/checkout@v4

      - name: Install stable toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Build p1
        run: cd p1 && cargo b --workspace --all-targets --all-features

      - name: Build p2
        run: cd p2 && cargo b --workspace --all-targets --all-features

  cargo-fmt:
    name: Cargo fmt
    runs-on: ubuntu-latest

    steps:
      - name: Fetch Repository
        uses: actions/checkout@v4

      - name: Install stable toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt

      - name: Rustfmt Check p1
        run: cd p1 && cargo fmt --all --check

      - name: Rustfmt Check p2
        run: cd p2 && cargo fmt --all --check

  cargo-clippy:
    name: Cargo clippy
    runs-on: ubuntu-latest

    steps:
      - name: Fetch Repository
        uses: actions/checkout@v4

      - name: Install stable toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy

      - name: Clippy Check p1
        run: cd p1 && cargo clippy --workspace --all-targets --all-features -- -Dwarnings 

      - name: Clippy Check p2
        run: cd p2 && cargo clippy --workspace --all-targets --all-features -- -Dwarnings 

  cargo-test:
    name: Cargo test
    runs-on: ubuntu-latest

    steps:
      - name: Fetch Repository
        uses: actions/checkout@v4

      - name: Install stable toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Cargo test
        run: cd p1 && cargo test --workspace --all-targets --all-features

      - name: Cargo test
        run: cd p2 && cargo test --workspace --all-targets --all-features
